name: Laravel CI/CD with SSH

on:
  push:
    branches:
      - main  # adjust if you use a different branch

jobs:
  laravel-tests:
    name: Run Laravel Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Setup .env
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run tests
        run: php artisan test

  deploy:
    name: Deploy to Personal Server
    needs: laravel-tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug SSH Connection
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "SSH connection successful"
            pwd
            whoami
            ls -la
            
      - name: Deploy via SSH
        if: success()
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Check if directory exists
            if [ -d "/home/malikan2/pys2" ]; then
              cd /home/malikan2/pys2
              git pull origin main
              composer install --no-dev --optimize-autoloader
              php artisan migrate --force
              php artisan db:seed --force
              php artisan config:cache
              php artisan route:cache
              php artisan view:cache
            else
              echo "Directory /home/malikan2/pys2 does not exist, creating it..."
              mkdir -p /home/malikan2/pys2
              cd /home/malikan2
              git clone https://github.com/malikandemir/project_finance_management.git pys2
              cd pys2
              composer install --no-dev --optimize-autoloader
              cp .env.example .env
              php artisan key:generate
              php artisan migrate --force
              php artisan db:seed --force
              php artisan config:cache
              php artisan route:cache
              php artisan view:cache
            fi
